// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminEquipmentItem } from './AdminEquipmentItem';

/**
 * Paginated admin equipment listing.
 */
export type AdminEquipmentPage = {
  items: Array<AdminEquipmentItem>;
  total: bigint;
  page: number;
  has_more: boolean;
};
