// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the super-admin equipment catalog manager. Unlike the public
 * catalog views, this exposes moderation metadata (status, submitter) and
 * every kind/status (not just `approved`).
 */
export type AdminEquipmentItem = {
  id: string;
  kind: string;
  brand: string;
  model: string;
  variant: string | null;
  display_name: string;
  canonical_name: string;
  usage_count: number;
  status: string;
  submitted_by_handle: string | null;
  created_at: string;
};
