// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiTokenCreated = {
  id: string;
  name: string;
  prefix: string;
  /**
   * Full secret — returned exactly once, at creation.
   */
  secret: string;
};
