// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for POST /api/photos/:id/apply-setup.
 */
export type ApplySetupInput = {
  setup_id: string;
  /**
   * "fill_empty" | "overwrite"
   */
  mode: string;
};
