// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = {
  signups_enabled: boolean;
  free_upload_max_mb: number;
  subscriber_upload_max_mb: number;
};
