// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishedItem } from "./PublishedItem";
import type { SkippedItem } from "./SkippedItem";

export type BatchPublishResponse = { published: Array<PublishedItem>, skipped: Array<SkippedItem>, };
