// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchApplyRequest = {
  ids: Array<string>;
  target: string | null;
  tags: Array<string> | null;
};
