// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraColorType } from './CameraColorType';
import type { CameraSensorType } from './CameraSensorType';

export type CameraSpecs = {
  sensor_type: CameraSensorType | null;
  color_type: CameraColorType | null;
  cooled: boolean | null;
  sensor_model: string | null;
  pixel_size_um: number | null;
  sensor_width_px: number | null;
  sensor_height_px: number | null;
  /**
   * Catalog v2 (migration 0022): completeness fields.
   */
  self_weight_g: number | null;
  full_well_capacity_e: number | null;
  read_noise_e: number | null;
  mount_thread: string | null;
  backfocus_mm: number | null;
};
