// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraColorType } from './CameraColorType';
import type { CameraSensorType } from './CameraSensorType';

export type CameraSpecs = {
  sensor_type: CameraSensorType | null;
  color_type: CameraColorType | null;
  cooled: boolean | null;
  sensor_model: string | null;
  pixel_size_um: number | null;
  sensor_width_px: number | null;
  sensor_height_px: number | null;
};
