// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One distinct catalog value (brand / model / variant) with how many items
 * currently use it — powers the assisted, duplicate-avoiding LOV inputs.
 */
export type CatalogValue = { value: string; count: number };
