// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogValue } from './CatalogValue';

/**
 * Cascading distinct values for the brand/model/variant pickers.
 * `brands` is always the distinct brands for the kind; `models` is populated
 * only when a brand is supplied; `variants` only when brand + model are.
 */
export type CatalogValues = {
  brands: Array<CatalogValue>;
  models: Array<CatalogValue>;
  variants: Array<CatalogValue>;
};
