// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPage } from './DiscoveryPage';

export type CategoryPage = { category: string; photo_count: bigint; page: DiscoveryPage };
