// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single celestial object identified in the photo's FOV by the
 * plate-solve identification job. Returned by
 * `GET /api/photos/:id/celestial-objects`. The frontend projects
 * `(rightAscension, declination)` → pixel coords client-side using the
 * photo's solve telemetry.
 */
export type CelestialObject = {
  slug: string;
  canonicalName: string;
  kind: string;
  objectType: string | null;
  magnitudeV: number | null;
  rightAscension: number;
  declination: number;
  majorAxisArcmin: number | null;
  minorAxisArcmin: number | null;
  positionAngleDeg: number | null;
  confidence: number;
};
