// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPhoto } from "./DiscoveryPhoto";

export type DiscoveryPage = { photos: Array<DiscoveryPhoto>, next_cursor: string | null, };
