// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DraftListItem = { id: string, short_id: string, original_name: string, target: string | null, status: string, created_at: string, 
/**
 * CDN URL for a small thumbnail.
 */
thumb_url: string, };
