// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentFacetBucket } from './EquipmentFacetBucket';

/**
 * Sidebar facets for the browse page. Each per-kind enum facet stays
 * `Some(_)` only when the kind has that field — irrelevant facets are
 * omitted so the frontend can branch on `Option::is_some()` rather
 * than counting empty vectors.
 */
export type EquipmentFacets = {
  brands: Array<EquipmentFacetBucket>;
  designs?: Array<EquipmentFacetBucket> | null;
  sensor_types?: Array<EquipmentFacetBucket> | null;
  color_types?: Array<EquipmentFacetBucket> | null;
  cooled?: Array<EquipmentFacetBucket> | null;
  mount_types?: Array<EquipmentFacetBucket> | null;
  filter_types?: Array<EquipmentFacetBucket> | null;
  modifier_types?: Array<EquipmentFacetBucket> | null;
  setup_kinds?: Array<EquipmentFacetBucket> | null;
};
