// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraSpecs } from './CameraSpecs';
import type { FilterSpecs } from './FilterSpecs';
import type { FocalModifierSpecs } from './FocalModifierSpecs';
import type { MountSpecs } from './MountSpecs';
import type { TelescopeSpecs } from './TelescopeSpecs';

/**
 * Tagged union — `kind` discriminator on the wire matches `equipment_items.kind`.
 */
export type EquipmentSpecsPayload =
  | ({ kind: 'telescope' } & TelescopeSpecs)
  | ({ kind: 'camera' } & CameraSpecs)
  | ({ kind: 'filter' } & FilterSpecs)
  | ({ kind: 'mount' } & MountSpecs)
  | ({ kind: 'focal_modifier' } & FocalModifierSpecs);
