// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSpecsPayload } from './EquipmentSpecsPayload';

/**
 * Body for POST /api/equipment/items resolve-or-create.
 */
export type EquipmentItemInput = {
  kind: string;
  display_name: string;
  /**
   * Optional per-kind specs to persist alongside the item row.
   * If present the `specs.kind` discriminator must match `kind` or the
   * request is rejected with 422. If absent the item is created (or
   * resolved) without touching any `<kind>_specs` table.
   */
  specs: EquipmentSpecsPayload | null;
};
