// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentFacets } from './EquipmentFacets';
import type { EquipmentItemDetail } from './EquipmentItemDetail';

/**
 * Page response for the browse endpoint. Items are fully expanded
 * (joined to their per-kind spec table) so the grid card can render
 * the right summary line without a second round trip.
 */
export type EquipmentCatalogResponse = {
  items: Array<EquipmentItemDetail>;
  facets: EquipmentFacets;
  total: bigint;
  /**
   * Page size used to compute `total / limit` pagination on the
   * frontend. Mirrors the request param (clamped server-side).
   */
  limit: bigint;
  offset: bigint;
};
