// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPage } from './DiscoveryPage';
import type { EquipmentMeta } from './EquipmentMeta';
import type { EquipmentPaired } from './EquipmentPaired';

export type EquipmentPage = {
  equipment: EquipmentMeta;
  paired: Array<EquipmentPaired>;
  page: DiscoveryPage;
};
