// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for POST /api/equipment/items resolve-or-create.
 */
export type EquipmentItemInput = { kind: string; display_name: string };
