// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One facet bucket: a category value and the number of items in the
 * catalog (for the given kind) that have that value.
 */
export type EquipmentFacetBucket = { value: string; count: bigint };
