// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EquipmentMeta = {
  id: string;
  kind: string;
  slug: string;
  canonical_name: string;
  display_name: string;
  photo_count: number;
};
