// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSpecsPayload } from './EquipmentSpecsPayload';

/**
 * Body for POST /api/equipment/items resolve-or-create.
 */
export type EquipmentItemInput = {
  kind: string;
  display_name: string;
  /**
   * Optional per-kind specs to persist alongside the item row.
   * If present the `specs.kind` discriminator must match `kind` or the
   * request is rejected with 422. If absent the item is created (or
   * resolved) without touching any `<kind>_specs` table.
   */
  specs: EquipmentSpecsPayload | null;
  /**
   * Catalog v2 (migration 0022): structured brand/model/variant.
   * All three are optional to preserve back-compat with callers that
   * only send `{ kind, display_name }` — when absent, the handler
   * derives brand="" and model=trim(display_name) (the freetext
   * fallback). When present, they take precedence and the handler
   * regenerates display_name + canonical_name from them.
   */
  brand: string | null;
  model: string | null;
  variant: string | null;
};
