// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EquipmentSummary = { telescope: string | null, camera: string | null, mount: string | null, filters: string | null, guiding: string | null, };
