// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSpecsPayload } from './EquipmentSpecsPayload';

export type EquipmentItemDetail = {
  id: string;
  kind: string;
  canonical_name: string;
  display_name: string;
  usage_count: number;
  status: string;
  submitted_by: string | null;
  approved_at: string | null;
  created_at: string;
  specs: EquipmentSpecsPayload | null;
  /**
   * Catalog v2 (migration 0022): structured brand/model/variant on
   * the shared header. `brand=""` denotes an unknown brand (typically
   * a freetext-created row that hasn't been moderated). `model` is
   * always populated.
   */
  brand: string;
  model: string;
  variant: string | null;
};
