// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Same-brand sibling of an equipment item. Brand prefix = first
 * whitespace-delimited token of `canonical_name` (e.g. "antlia" for
 * "Antlia 3nm Hα Pro"). Items whose canonical_name has no space are
 * considered brand-less and produce no siblings.
 */
export type EquipmentSibling = {
  kind: string;
  slug: string;
  display_name: string;
  usage_count: number;
};
