// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One canonical equipment item (used inside a setup).
 */
export type EquipmentItemRef = {
  id: string;
  kind: string;
  canonical_name: string;
  display_name: string;
  /**
   * Catalog v2 (migration 0022): structured brand/model/variant on
   * the shared header. `brand=""` denotes an unknown brand.
   */
  brand: string;
  model: string;
  variant?: string | null;
};
