// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSpecsPayload } from './EquipmentSpecsPayload';

export type EquipmentItemPatch = {
  display_name?: string | null;
  specs?: EquipmentSpecsPayload | null;
};
