// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeaturedPhotoSummary = { id: string, short_id: string, featured_position: number, target: string | null, appreciations_count: number, blurhash: string | null, width: number | null, height: number | null, };
