// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-filter integration row: how many sub-frames at what exposure,
 * for a given filter. Display-only acquisition detail stored as a JSONB
 * list on `photos.filter_integrations` (independent of the filter chips,
 * so luminance — which is not a chip — is representable). Per-filter and
 * grand totals are derived client-side (`sub_count * sub_exposure_s`).
 */
export type FilterIntegration = {
  /**
   * Filter band ALIAS / display label: "L" | "R" | "G" | "B" | "Ha" |
   * "OIII" | "SII" | free text. Read from the master's FITS FILTER
   * keyword; this is a short code, not a catalog reference.
   */
  filter: string;
  /**
   * Number of integrated sub-frames. >= 0.
   */
  sub_count: number;
  /**
   * Per-sub exposure in seconds. >= 0.
   */
  sub_exposure_s: number;
  /**
   * Optional link to a real catalog filter (`equipment_items.id`,
   * kind='filter'). The header `filter` is only an alias; the user
   * reconciles it to a catalog item (auto-matched on drop, overridable).
   * `None` when the band has no catalog entry — e.g. Luminance for a
   * photographer who keeps no L filter in their catalog.
   */
  filter_item_id: string | null;
  /**
   * Per-session camera gain (unitless ZWO/CMOS setting, FITS `GAIN`).
   * Session-specific, so it lives here rather than the global
   * `photos.gain` column — R and Hα are often shot at different gains.
   * `None` when unknown. See `docs/superpowers/specs/2026-05-27-
   * acquisition-session-fields-design.md`.
   */
  gain: number | null;
  /**
   * Per-session sensor temperature in °C (FITS `CCD-TEMP`, actual,
   * preferred over `SET-TEMP`). Nullable; legitimately negative.
   */
  sensor_temp_c: number | null;
};
