// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSize } from './FilterSize';
import type { FilterType } from './FilterType';

export type FilterSpecs = {
  filter_type: FilterType | null;
  bandwidth_nm: number | null;
  size: FilterSize | null;
  mounted: boolean | null;
  /**
   * Catalog v2 (migration 0022): completeness fields.
   */
  mounted_diameter_mm?: number | null;
  thickness_mm?: number | null;
  peak_transmission_pct?: number | null;
};
