// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterSize =
  | '1_25in'
  | '2in'
  | '31mm'
  | '36mm'
  | '50mm_round'
  | '50mm_square'
  | 'other';
