// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-filter integration row: how many sub-frames at what exposure,
 * for a given filter. Display-only acquisition detail stored as a JSONB
 * list on `photos.filter_integrations` (independent of the filter chips,
 * so luminance — which is not a chip — is representable). Per-filter and
 * grand totals are derived client-side (`sub_count * sub_exposure_s`).
 */
export type FilterIntegration = {
  /**
   * Filter band: "L" | "R" | "G" | "B" | "Ha" | "OIII" | "SII" | free text.
   */
  filter: string;
  /**
   * Number of integrated sub-frames. >= 0.
   */
  sub_count: number;
  /**
   * Per-sub exposure in seconds. >= 0.
   */
  sub_exposure_s: number;
};
