// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FocalModifierType } from './FocalModifierType';

export type FocalModifierSpecs = {
  modifier_type: FocalModifierType | null;
  factor: number | null;
  /**
   * Catalog v2 (migration 0022): completeness fields.
   */
  self_weight_g: number | null;
  backfocus_mm: number | null;
  image_circle_mm: number | null;
};
