// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalleryPhoto } from './GalleryPhoto';

export type GalleryPage = {
  photos: Array<GalleryPhoto>;
  /**
   * Opaque cursor; pass back as `?cursor=` to load the next page. `None` when exhausted.
   */
  next_cursor: string | null;
};
