// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuidingSetupKind } from './GuidingSetupKind';

/**
 * Catalog v2 (migration 0022): guiding equipment spec sub-table.
 * `setup_kind` is required (the DB CHECK enforces it); the rest are
 * optional just like the other spec structs.
 */
export type GuidingSpecs = {
  setup_kind: GuidingSetupKind | null;
  guide_focal_mm?: number | null;
  guide_aperture_mm?: number | null;
  guide_camera?: string | null;
};
