// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeroStats = { frames: bigint, integration_seconds: bigint, followers: bigint, appreciations: bigint, targets: bigint, member_since_year: number, };
