// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeroStats = {
  frames: number;
  integration_seconds: number;
  followers: number;
  appreciations: number;
  targets: number;
  member_since_year: number;
};
