// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HintSource = {
  ra: string;
  dec: string;
  scale: string;
  rotation: string | null;
  epoch: string | null;
};
