// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationSummary = { location_text: string | null, bortle_class: number | null, sqm: number | null, };
