// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeStats = { published_count: bigint, draft_count: bigint, integration_secs: number, appreciations_received: bigint, };
