// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeStats = {
  published_count: number;
  draft_count: number;
  integration_secs: number;
  appreciations_received: number;
};
