// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountType } from './MountType';

export type MountSpecs = {
  mount_type: MountType | null;
  payload_kg: number | null;
  goto: boolean | null;
};
