// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MountType =
  | 'equatorial_german'
  | 'equatorial_fork'
  | 'alt_az'
  | 'harmonic_drive'
  | 'strain_wave'
  | 'other';
