// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acquisition / observation facts pulled from the XISF header's FITS
 * keywords and `Instrument:*` / `Observation:*` PCL properties. This is
 * the reliable, local source for the photo page's technical card (the
 * plate-solve service only echoes a subset).
 *
 * See also [`crate::photos::xisf_display::XisfDisplayMeta`] — the
 * owner-only verify-form view over the plate-solve embed JSON;
 * deliberately separate, not a duplicate.
 */
export type ObservationSummary = {
  filter: string | null;
  telescope: string | null;
  focalLengthMm: number | null;
  pixelSizeUm: number | null;
  binning: number | null;
  pixelScaleArcsec: number | null;
  observationStart: string | null;
  observationEnd: string | null;
  siteLatitude: number | null;
  siteLongitude: number | null;
  siteElevationM: number | null;
};
