// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchTargetsItem } from "./PatchTargetsItem";

export type PatchTargetsResponse = { targets: Array<PatchTargetsItem>, };
