// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchTargetsItem = { slug: string; canonical_name: string; is_primary: boolean };
