// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single row in the /api/photographers index. Has just enough to render
 * a tile (name + handle + cover photo) plus the headline stats users
 * sort against (frames, followers, integration).
 */
export type PhotographerListItem = {
  handle: string;
  display_name: string;
  frame_count: bigint;
  follower_count: bigint;
  integration_seconds: bigint;
  cover_photo_id: string | null;
  member_since_year: number;
};
