// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterType } from './FilterType';

export type PhotoFilterChip = {
  id: string;
  display_name: string;
  filter_type: FilterType | null;
  bandwidth_nm: number | null;
  position: number;
};
