// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoDetail = {
  id: string;
  owner_id: string;
  short_id: string;
  status: string;
  original_name: string;
  bytes: bigint;
  mime: string;
  width: number | null;
  height: number | null;
  camera: string | null;
  lens: string | null;
  iso: number | null;
  exposure_s: number | null;
  focal_mm: number | null;
  /**
   * Migration 0013: extended acquisition fields surfaced on the verify form.
   */
  aperture_f: number | null;
  gain: number | null;
  sensor_temp_c: number | null;
  sessions: number | null;
  /**
   * Plate-solving result. Today filled manually on the verify form;
   * a future plate-solve job will populate these from astrometry.
   */
  ra_deg: number | null;
  dec_deg: number | null;
  target: string | null;
  caption: string | null;
  taken_at: string | null;
  created_at: string;
  appreciation_count: bigint;
  comment_count: bigint;
  is_draft: boolean;
  last_step: string | null;
  replaced_at: string | null;
  original_uploaded_at: string;
  pipeline_error: string | null;
};
