// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhotographerListItem } from "./PhotographerListItem";

export type PhotographerIndexPage = { items: Array<PhotographerListItem>, next_cursor: string | null, };
