// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlatesolveState = 'idle' | 'solving' | 'solved' | 'failed';

/**
 * Shape returned by `/platesolve-status`. The `state` discriminant
 * is what the UI branches on; the other fields are populated only
 * when relevant to the state (telemetry on `Solved`, message on
 * `Failed`).
 */
export type PlatesolveStatus = {
  /**
   * One of `idle` / `solving` / `solved` / `failed`. Discriminator
   * for the UI; the JSON body always includes the same field set
   * so frontend types stay stable.
   */
  state: PlatesolveState;
  /**
   * Human-readable failure reason. Populated only when
   * `state == Failed`. (We deliberately surface the
   * `ABORTED_SENTINEL` string as a regular failure so the UI can
   * render "you can retry to clear" without special-casing it.)
   */
  error: string | null;
  /**
   * RFC 3339 timestamp of the successful solve. Populated only
   * when `state == Solved`.
   */
  solvedAt: string | null;
  raDeg: number | null;
  decDeg: number | null;
  pixelScaleArcsec: number | null;
  rotationDeg: number | null;
  rmsArcsec: number | null;
  matchedCount: number | null;
  detectedCount: number | null;
};
