// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitsKeyword } from './FitsKeyword';
import type { HintSource } from './HintSource';
import type { PclProperty } from './PclProperty';
import type { Render } from './Render';
import type { Wcs } from './Wcs';

/**
 * Successful solve. Field names mirror the server's `SolveResp`.
 */
export type PlatesolveResult = {
  wcs: Wcs;
  rmsArcsec: number;
  matchedCount: number;
  detectedCount: number;
  iterations: number;
  obsEpochJyear: number;
  hintSource: HintSource;
  fits: Array<FitsKeyword>;
  pclProperties: Array<PclProperty>;
  hasDistortion: boolean;
  elapsedMs: bigint;
  /**
   * Present iff `SolveOptions::render == Some(true)` AND the
   * service successfully decoded the XISF into a JPEG. Render
   * failure on the success path is non-fatal — the field is
   * omitted and the WCS still ships, so callers must `match`
   * rather than assume.
   */
  render: Render | null;
};
