// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from './KeyValue';
import type { ProcessTable } from './ProcessTable';

export type ProcessStep = {
  position: number;
  className: string;
  label: string;
  category: string;
  summary: string | null;
  version: string | null;
  enabled: boolean;
  startedAt: string | null;
  durationS: number | null;
  params: Array<KeyValue>;
  tables: Array<ProcessTable>;
};
