// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayStretch } from './DisplayStretch';
import type { ObservationSummary } from './ObservationSummary';
import type { ProcessStep } from './ProcessStep';
import type { WhiteBalance } from './WhiteBalance';

export type ProcessingReport = {
  creatorApp: string | null;
  creatorModule: string | null;
  creatorOs: string | null;
  createdAt: string | null;
  displayStretch: DisplayStretch | null;
  whiteBalance: WhiteBalance | null;
  observation: ObservationSummary | null;
  totalDurationS: number | null;
  pipeline: Array<ProcessStep>;
};
