// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSummary } from './EquipmentSummary';
import type { LocationSummary } from './LocationSummary';
import type { SocialLink } from './SocialLink';

/**
 * Authenticated owner's view of their own profile (writable surface).
 */
export type Profile = {
  display_name: string;
  tagline: string | null;
  bio_html: string | null;
  cover_photo_id: string | null;
  equipment: EquipmentSummary;
  location: LocationSummary;
  social_links: Array<SocialLink>;
};
