// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentSummary } from './EquipmentSummary';
import type { FeaturedPhotoSummary } from './FeaturedPhotoSummary';
import type { HeroStats } from './HeroStats';
import type { LocationSummary } from './LocationSummary';
import type { SocialLink } from './SocialLink';

/**
 * Public read-side aggregator returned by GET /api/users/by-handle/:handle/profile.
 */
export type PublicProfile = {
  id: string;
  handle: string;
  display_name: string;
  tagline: string | null;
  bio_html: string | null;
  cover: FeaturedPhotoSummary | null;
  /**
   * Current avatar id (rendered via the CDN at `/img/<avatar_id>`), or null.
   */
  avatar_id: string | null;
  equipment: EquipmentSummary;
  location: LocationSummary;
  social_links: Array<SocialLink>;
  stats: HeroStats;
  featured: Array<FeaturedPhotoSummary>;
};
