// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display-ready JPEG bundled with the solve response. The bytes are
 * base64-encoded over the wire (33 % size inflation accepted in
 * exchange for keeping the multipart parser simple on both ends).
 * Decode with `base64::engine::general_purpose::STANDARD.decode(...)`
 * before persisting to S3.
 */
export type Render = { mime: string; width: number; height: number; bytesB64: string };
