// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPhoto } from './DiscoveryPhoto';
import type { SearchTargetHit } from './SearchTargetHit';
import type { SearchUserHit } from './SearchUserHit';

export type SearchResults = {
  q: string;
  targets: Array<SearchTargetHit>;
  users: Array<SearchUserHit>;
  photos: Array<DiscoveryPhoto>;
};
