// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionRow = { id: string, browser: string, browser_version: string, os: string, os_version: string, category: string, ip: string, last_used_at: string, created_at: string, is_current: boolean, };
