// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleCount } from './RoleCount';

/**
 * Compact list-view summary — metadata + counts per role.
 */
export type SetupSummary = {
  id: string;
  name: string;
  description: string | null;
  location: string | null;
  is_remote: boolean;
  is_default: boolean;
  guiding: string | null;
  /**
   * "overwrite" | "fill_empty"
   */
  default_apply_mode: string;
  updated_at: string;
  /**
   * One entry per role with at least one item.
   */
  item_counts: Array<RoleCount>;
};
