// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquipmentItemRef } from './EquipmentItemRef';

/**
 * One member of a setup (link between a setup and a canonical item).
 */
export type SetupItem = { role: string; item: EquipmentItemRef };
