// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupItem } from './SetupItem';

/**
 * Detail-view setup with full item expansion.
 */
export type SetupDetail = {
  id: string;
  name: string;
  description: string | null;
  location: string | null;
  is_remote: boolean;
  is_default: boolean;
  guiding: string | null;
  created_at: string;
  updated_at: string;
  items: Array<SetupItem>;
};
