// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupInputItem } from './SetupInputItem';

/**
 * Body for POST/PATCH /api/equipment/setups[/:id]. Items replace-all
 * on PATCH (no merge). Unknown item_ids → 422.
 */
export type SetupInput = {
  name: string;
  description: string | null;
  location: string | null;
  is_remote: boolean;
  is_default: boolean;
  guiding: string | null;
  /**
   * "overwrite" | "fill_empty"
   */
  default_apply_mode: string;
  items: Array<SetupInputItem>;
};
