// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global counts for the home-page hero band. Cached aggressively at
 * the CDN edge; the numbers move slowly (an upload changes one).
 */
export type SiteStats = { practitioners: bigint; frames: bigint; integration_seconds: bigint };
