// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional hint overrides for the solve. Every field set takes
 * precedence over what the server extracts from the XISF header.
 * Mirrors `xisf-rs-platesolve-server::handlers::solve::SolveOptions`
 * — keep field names in sync.
 */
export type SolveOptions = {
  raDeg: number | null;
  decDeg: number | null;
  pixelScaleArcsec: number | null;
  rotationDeg: number | null;
  flipX: boolean | null;
  obsEpochJyear: number | null;
  maxCatalogStars: number | null;
  magnitudeLimit: number | null;
  imageIndex: number | null;
  detectionThreshold: number | null;
  /**
   * Ask the service to bundle a display-ready JPEG render of the
   * XISF in the response. When `Some(true)`, the response gains a
   * [`Render`] field. Default `None` (no render) keeps the
   * existing contract for callers that only want the WCS.
   */
  render: boolean | null;
};
