// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTier } from './UserTier';

export type StorageSummary = {
  /**
   * Sum of `photos.bytes` for rows owned by the caller. Doesn't
   * include thumbnails or display masters.
   */
  used_bytes: number;
  /**
   * Tier-derived ceiling, used by the upload page footer to render
   * "STORAGE · 1.84 / 5.00 GB USED". Soft signal only — per-file
   * size enforcement lives in the upload-init handler.
   */
  quota_bytes: number;
  tier: UserTier;
};
