// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveryPage } from './DiscoveryPage';
import type { TagMeta } from './TagMeta';

export type TagPage = { tag: TagMeta; page: DiscoveryPage };
