// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetMeta = { slug: string, canonical_name: string, aliases: Array<string>, kind: string | null, photo_count: bigint, contributor_count: bigint, };
