// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetPreviewThumb } from "./TargetPreviewThumb";

export type TargetListItem = { slug: string, canonical_name: string, object_type: string | null, constellation: string | null, magnitude_v: number | null, photo_count: bigint, preview_thumbs: Array<TargetPreviewThumb>, };
