// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetPreviewThumb = { 
/**
 * UUID of the photo — used to build CDN URLs via `/cdn/img/<photo_id>`.
 */
photo_id: string, 
/**
 * Short human-readable ID — used to build permalink URLs `/u/<handle>/p/<short_id>`.
 */
short_id: string, blurhash: string | null, };
