// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetMeta = {
  slug: string;
  canonical_name: string;
  aliases: Array<string>;
  kind: string | null;
  photo_count: bigint;
  contributor_count: bigint;
  right_ascension: number | null;
  declination: number | null;
  magnitude_v: number | null;
  object_type: string | null;
  constellation: string | null;
  major_axis_arcmin: number | null;
  minor_axis_arcmin: number | null;
};
