// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetMeta = {
  slug: string;
  canonical_name: string;
  aliases: Array<string>;
  kind: string | null;
  photo_count: number;
  contributor_count: number;
  right_ascension: number | null;
  declination: number | null;
  magnitude_v: number | null;
  object_type: string | null;
  constellation: string | null;
  major_axis_arcmin: number | null;
  minor_axis_arcmin: number | null;
  /**
   * Day-of-year (1..365) on which the object reaches opposition — it sits
   * opposite the Sun and transits at local midnight, its best-observation
   * date. Approximate (±a few days). See crate::discovery::opposition.
   */
  opposition_doy: number | null;
};
