// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetListItem } from "./TargetListItem";

export type TargetIndexPage = { targets: Array<TargetListItem>, next_cursor: string | null, };
