// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelescopeDesign =
  | 'refractor_apo'
  | 'refractor_achro'
  | 'sct'
  | 'rc'
  | 'newtonian'
  | 'maksutov_cassegrain'
  | 'maksutov_newtonian'
  | 'dall_kirkham'
  | 'other';
