// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelescopeDesign } from './TelescopeDesign';

export type TelescopeSpecs = {
  design: TelescopeDesign | null;
  aperture_mm: number | null;
  focal_length_mm: number | null;
  /**
   * Computed (DB-generated). Returned in GET, ignored in PATCH/POST.
   */
  focal_ratio_f: number | null;
  /**
   * Catalog v2 (migration 0022): completeness fields.
   */
  self_weight_kg: number | null;
  optical_length_mm: number | null;
  backfocus_mm: number | null;
};
