// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTier } from "./UserTier";

export type User = { id: string, email: string, display_name: string, 
/**
 * URL handle — used to build /u/<handle> profile URLs from the
 * session user without a second round-trip to look it up.
 */
handle: string, created_at: string, following_ids: Array<string>, pending_deletion_at: string | null, tier: UserTier, 
/**
 * Current avatar id, or null if none. The image renders through the
 * CDN at `/img/<avatar_id>` (key `display/<avatar_id>.jpg`).
 */
avatar_id: string | null, 
/**
 * Super-admin flag. Gates the `/admin` UI and the `/api/admin/*` API.
 */
is_admin: boolean, };
