// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTier } from "./UserTier";

export type User = { id: string, email: string, display_name: string, created_at: string, following_ids: Array<string>, pending_deletion_at: string | null, tier: UserTier, };
