// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Wcs = {
  raDeg: number;
  decDeg: number;
  pixelScaleArcsec: number;
  rotationDeg: number;
  flipX: boolean;
  crpixX: number;
  crpixY: number;
  cd: [[number, number], [number, number]];
};
