// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Processing-history fields we can pull out of a plate-solve
 * response. Every field is optional — XISFs from different
 * processing tools carry different subsets.
 */
export type XisfDisplayMeta = {
  /**
   * Filter band (Hα, L, R, G, B, OIII, …). Read from FITS
   * `FILTER` first, falls back to PCL `Instrument:Filter:Name`.
   */
  filter: string | null;
  /**
   * Telescope name (`TELESCOP` / `Instrument:Telescope:Name`).
   */
  telescope: string | null;
  /**
   * First sub-exposure start. RFC 3339. Useful as a "session"
   * marker; the difference with [`Self::observation_end`] is a
   * strong signal that the XISF is a multi-night stack.
   */
  observationStart: string | null;
  /**
   * Last sub-exposure end. RFC 3339.
   */
  observationEnd: string | null;
  /**
   * Observatory geographic coordinates, if the file carries them.
   */
  latitudeDeg: number | null;
  longitudeDeg: number | null;
  elevationM: number | null;
  /**
   * Sub-frame count when the integration tool wrote an explicit
   * `NCOMBINE` FITS keyword or `Process:Integration:ImageCount`
   * PCL property. Many real-world XISFs omit this; in that case
   * the UI shows nothing here and relies on the time span instead.
   */
  subframes: number | null;
  /**
   * Filter binning (`XBINNING` / `Instrument:Camera:XBinning`).
   * Mostly 1 in practice but useful for diagnostics.
   */
  binningX: number | null;
  binningY: number | null;
  /**
   * Free-text FITS `HISTORY` lines collected from the file. The
   * XISF format keeps one `HISTORY` per logical processing step
   * (calibration, registration, integration) — each rendered as
   * a separate entry here. Empty lines and whitespace-only entries
   * are filtered out.
   */
  history: Array<string>;
};
